- name: Build and Deploy petstore1
  hosts: local
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "muralidharan96"
        password: "dckr_pat_GOKrQcbCAlJuX2DAOkVz4-bFuBQ"

    - name: Build and Push Docker image
      community.docker.docker_image:
        name: "muralidharan96/petstore1"
        tag: latest
        build:
          path: /var/lib/jenkins/workspace/petstore
        push: yes
        source: build

    - name: Run Petstore container
      community.docker.docker_container:
        name: pet1
        image: "muralidharan96/petstore1:latest"
        state: started
        restart_policy: always
        published_ports:
          - "8081:8080"
